/*
populate tbl_state 
*/

INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Alaska','AK');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Alabama','AL');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Arkansas','AR');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Arizona','AZ');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('California','CA');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Colorado','CO');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Connecticut','CT');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('District of Columbia','DC');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Delaware','DE');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Florida','FL');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Georgia','GA');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Hawaii','HI');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Iowa','IA');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Idaho','ID');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Illinois','IL');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Indiana','IN');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Kansas','KS');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Kentucky','KY');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Louisiana','LA');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Massachusetts','MA');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Maryland','MD');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Maine','ME');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Michigan','MI');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Minnesota','MN');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Missouri','MO');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Mississippi','MS');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Montana','MT');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('North Carolina','NC');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('North Dakota','ND');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Nebraska','NE');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('New Hampshire','NH');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('New Jersey','NJ');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('New Mexico','NM');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Nevada','NV');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('New York','NY');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Ohio','OH');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Oklahoma','OK');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Oregon','OR');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Pennsylvania','PA');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Rhode Island','RI');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('South Carolina','SC');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('South Dakota','SD');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Tennessee','TN');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Texas','TX');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Utah','UT');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Virginia','VA');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Vermont','VT');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Washington','WA');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Wisconsin','WI');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('West Virginia','WV');
INSERT INTO `tbl_state` (`state_name`,`state_code`) VALUES ('Wyoming','WY');
